language: node_js

node_js:
  - "4"

matrix:
  allow_failures:

install:
  - npm install -g npm@1.4.23
  - npm --version
  - npm install

script:
  - npm test

after_script:
  - echo "========== test log: ============"
  - pwd
  - ls -al
  - ls -al test/output
  - cat test/output/*.log
