// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: 'a0d901ba-9956-4f7d-830c-2d7974c36666',
    name: 'Azure Storage DM Dev',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    _eventsCount: '1',
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_CONNECTION_STRING'] = 'DefaultEndpointsProtocol=https;AccountName=xplat;AccountKey=null';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://xplat.blob.core.windows.net:443')
  .head('/storage-cli-blob-test/blockblobname962628554157')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b52d0672-0001-0029-33aa-3fe045000000',
  'x-ms-version': '2015-12-11',
  date: 'Wed, 16 Nov 2016 01:40:37 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.blob.core.windows.net:443')
  .head('/storage-cli-blob-test/blockblobname962628554157')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b52d0672-0001-0029-33aa-3fe045000000',
  'x-ms-version': '2015-12-11',
  date: 'Wed, 16 Nov 2016 01:40:37 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/storage-cli-blob-test/blockblobname962628554157', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'aOEJ8PQMpyoV4FzCJ4b45g==',
  'last-modified': 'Wed, 16 Nov 2016 01:40:38 GMT',
  etag: '"0x8D40DC1914F54AF"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b79c609b-0001-000a-4baa-3f8f8e000000',
  'x-ms-version': '2015-12-11',
  'x-ms-request-server-encrypted': 'false',
  date: 'Wed, 16 Nov 2016 01:40:37 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/storage-cli-blob-test/blockblobname962628554157', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'aOEJ8PQMpyoV4FzCJ4b45g==',
  'last-modified': 'Wed, 16 Nov 2016 01:40:38 GMT',
  etag: '"0x8D40DC1914F54AF"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b79c609b-0001-000a-4baa-3f8f8e000000',
  'x-ms-version': '2015-12-11',
  'x-ms-request-server-encrypted': 'false',
  date: 'Wed, 16 Nov 2016 01:40:37 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.blob.core.windows.net:443')
  .head('/storage-cli-blob-test/blockblobname962628554157')
  .reply(200, "", { 'content-length': '10',
  'content-type': 'plain/text',
  'content-md5': 'aOEJ8PQMpyoV4FzCJ4b45g==',
  'last-modified': 'Wed, 16 Nov 2016 01:40:38 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D40DC1914F54AF"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '1004f127-0001-003b-16aa-3fd459000000',
  'x-ms-version': '2015-12-11',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  date: 'Wed, 16 Nov 2016 01:40:38 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.blob.core.windows.net:443')
  .head('/storage-cli-blob-test/blockblobname962628554157')
  .reply(200, "", { 'content-length': '10',
  'content-type': 'plain/text',
  'content-md5': 'aOEJ8PQMpyoV4FzCJ4b45g==',
  'last-modified': 'Wed, 16 Nov 2016 01:40:38 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D40DC1914F54AF"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '1004f127-0001-003b-16aa-3fd459000000',
  'x-ms-version': '2015-12-11',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  date: 'Wed, 16 Nov 2016 01:40:38 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.blob.core.windows.net:443')
  .head('/storage-cli-blob-test/blockblobname962628554157')
  .reply(200, "", { 'content-length': '10',
  'content-type': 'plain/text',
  'content-md5': 'aOEJ8PQMpyoV4FzCJ4b45g==',
  'last-modified': 'Wed, 16 Nov 2016 01:40:38 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D40DC1914F54AF"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'bf8da88a-0001-001c-13aa-3f4e10000000',
  'x-ms-version': '2015-12-11',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  date: 'Wed, 16 Nov 2016 01:40:38 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.blob.core.windows.net:443')
  .head('/storage-cli-blob-test/blockblobname962628554157')
  .reply(200, "", { 'content-length': '10',
  'content-type': 'plain/text',
  'content-md5': 'aOEJ8PQMpyoV4FzCJ4b45g==',
  'last-modified': 'Wed, 16 Nov 2016 01:40:38 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D40DC1914F54AF"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'bf8da88a-0001-001c-13aa-3f4e10000000',
  'x-ms-version': '2015-12-11',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  date: 'Wed, 16 Nov 2016 01:40:38 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.blob.core.windows.net:443')
  .head('/storage-cli-blob-test/blockblobname962628554157')
  .reply(200, "", { 'content-length': '10',
  'content-type': 'plain/text',
  'content-md5': 'aOEJ8PQMpyoV4FzCJ4b45g==',
  'last-modified': 'Wed, 16 Nov 2016 01:40:38 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D40DC1914F54AF"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '685c39af-0001-0010-4aaa-3fa0e1000000',
  'x-ms-version': '2015-12-11',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  date: 'Wed, 16 Nov 2016 01:40:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.blob.core.windows.net:443')
  .head('/storage-cli-blob-test/blockblobname962628554157')
  .reply(200, "", { 'content-length': '10',
  'content-type': 'plain/text',
  'content-md5': 'aOEJ8PQMpyoV4FzCJ4b45g==',
  'last-modified': 'Wed, 16 Nov 2016 01:40:38 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D40DC1914F54AF"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '685c39af-0001-0010-4aaa-3fa0e1000000',
  'x-ms-version': '2015-12-11',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  date: 'Wed, 16 Nov 2016 01:40:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.blob.core.windows.net:443')
  .put('/storage-cli-blob-test/blockblobname962628554157?comp=properties')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 16 Nov 2016 01:40:40 GMT',
  etag: '"0x8D40DC19291CCFA"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '7a8d8af6-0001-0006-15aa-3f617f000000',
  'x-ms-version': '2015-12-11',
  date: 'Wed, 16 Nov 2016 01:40:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.blob.core.windows.net:443')
  .put('/storage-cli-blob-test/blockblobname962628554157?comp=properties')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 16 Nov 2016 01:40:40 GMT',
  etag: '"0x8D40DC19291CCFA"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '7a8d8af6-0001-0006-15aa-3f617f000000',
  'x-ms-version': '2015-12-11',
  date: 'Wed, 16 Nov 2016 01:40:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.blob.core.windows.net:443')
  .head('/storage-cli-blob-test/blockblobname962628554157')
  .reply(200, "", { 'content-length': '10',
  'content-type': 'text/xml',
  'content-md5': 'aOEJ8PQMpyoV4FzCJ4b45g==',
  'last-modified': 'Wed, 16 Nov 2016 01:40:40 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D40DC19291CCFA"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c16598bc-0001-0004-19aa-3f6385000000',
  'x-ms-version': '2015-12-11',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  date: 'Wed, 16 Nov 2016 01:40:41 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.blob.core.windows.net:443')
  .head('/storage-cli-blob-test/blockblobname962628554157')
  .reply(200, "", { 'content-length': '10',
  'content-type': 'text/xml',
  'content-md5': 'aOEJ8PQMpyoV4FzCJ4b45g==',
  'last-modified': 'Wed, 16 Nov 2016 01:40:40 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D40DC19291CCFA"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c16598bc-0001-0004-19aa-3f6385000000',
  'x-ms-version': '2015-12-11',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'false',
  date: 'Wed, 16 Nov 2016 01:40:41 GMT',
  connection: 'close' });
 return result; }]];
 exports.randomTestIdsGenerated = function() { return ['blockblobname962628554157'];};