// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '9532a63e-f2eb-4649-bb23-5ed01077ce80',
    name: 'franks-official-test-sub',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    _eventsCount: '1',
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_VM_TEST_LOCATION'] = 'westcentralus';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName?api-version=2017-09-01')
  .reply(404, "{\r\n  \"error\": {\r\n    \"code\": \"NotFound\",\r\n    \"message\": \"Resource /subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName not found.\",\r\n    \"details\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '299',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '6a80918b-e308-4ae6-85cf-893ff055ec28',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-correlation-request-id': 'a5fd50a5-ef99-4ed1-9197-9032123addfa',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120115Z:a5fd50a5-ef99-4ed1-9197-9032123addfa',
  date: 'Thu, 05 Oct 2017 12:01:15 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName?api-version=2017-09-01')
  .reply(404, "{\r\n  \"error\": {\r\n    \"code\": \"NotFound\",\r\n    \"message\": \"Resource /subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName not found.\",\r\n    \"details\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '299',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '6a80918b-e308-4ae6-85cf-893ff055ec28',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-correlation-request-id': 'a5fd50a5-ef99-4ed1-9197-9032123addfa',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120115Z:a5fd50a5-ef99-4ed1-9197-9032123addfa',
  date: 'Thu, 05 Oct 2017 12:01:15 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName?api-version=2017-09-01', '*')
  .reply(201, "{\r\n  \"name\": \"singularPrefixesName\",\r\n  \"id\": \"/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName\",\r\n  \"etag\": \"W/\\\"15348ade-8dd9-48eb-973c-6ceb106c9091\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Updating\",\r\n    \"description\": \"testDesc\",\r\n    \"protocol\": \"*\",\r\n    \"sourcePortRange\": \"1025-1030\",\r\n    \"destinationPortRange\": \"4242\",\r\n    \"sourceAddressPrefix\": \"10.0.0.0/16\",\r\n    \"destinationAddressPrefix\": \"11.0.0.0/24\",\r\n    \"access\": \"Allow\",\r\n    \"priority\": 1470,\r\n    \"direction\": \"Inbound\",\r\n    \"sourcePortRanges\": [],\r\n    \"destinationPortRanges\": [],\r\n    \"sourceAddressPrefixes\": [],\r\n    \"destinationAddressPrefixes\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '793',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'retry-after': '10',
  'x-ms-request-id': '1bb6b4d4-6f1d-4136-b8ce-069c4bd29678',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/providers/Microsoft.Network/locations/westcentralus/operations/1bb6b4d4-6f1d-4136-b8ce-069c4bd29678?api-version=2017-09-01',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-correlation-request-id': 'db9217d2-8986-4b32-af8a-5487dd851b9d',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120117Z:db9217d2-8986-4b32-af8a-5487dd851b9d',
  date: 'Thu, 05 Oct 2017 12:01:16 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName?api-version=2017-09-01', '*')
  .reply(201, "{\r\n  \"name\": \"singularPrefixesName\",\r\n  \"id\": \"/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName\",\r\n  \"etag\": \"W/\\\"15348ade-8dd9-48eb-973c-6ceb106c9091\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Updating\",\r\n    \"description\": \"testDesc\",\r\n    \"protocol\": \"*\",\r\n    \"sourcePortRange\": \"1025-1030\",\r\n    \"destinationPortRange\": \"4242\",\r\n    \"sourceAddressPrefix\": \"10.0.0.0/16\",\r\n    \"destinationAddressPrefix\": \"11.0.0.0/24\",\r\n    \"access\": \"Allow\",\r\n    \"priority\": 1470,\r\n    \"direction\": \"Inbound\",\r\n    \"sourcePortRanges\": [],\r\n    \"destinationPortRanges\": [],\r\n    \"sourceAddressPrefixes\": [],\r\n    \"destinationAddressPrefixes\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '793',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'retry-after': '10',
  'x-ms-request-id': '1bb6b4d4-6f1d-4136-b8ce-069c4bd29678',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/providers/Microsoft.Network/locations/westcentralus/operations/1bb6b4d4-6f1d-4136-b8ce-069c4bd29678?api-version=2017-09-01',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-correlation-request-id': 'db9217d2-8986-4b32-af8a-5487dd851b9d',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120117Z:db9217d2-8986-4b32-af8a-5487dd851b9d',
  date: 'Thu, 05 Oct 2017 12:01:16 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/providers/Microsoft.Network/locations/westcentralus/operations/1bb6b4d4-6f1d-4136-b8ce-069c4bd29678?api-version=2017-09-01')
  .reply(200, "{\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '29',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'c1a87584-4565-4266-9d3b-d7abe451661a',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14993',
  'x-ms-correlation-request-id': 'da3dfd55-9155-4688-8771-be7f07cec234',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120147Z:da3dfd55-9155-4688-8771-be7f07cec234',
  date: 'Thu, 05 Oct 2017 12:01:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/providers/Microsoft.Network/locations/westcentralus/operations/1bb6b4d4-6f1d-4136-b8ce-069c4bd29678?api-version=2017-09-01')
  .reply(200, "{\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '29',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'c1a87584-4565-4266-9d3b-d7abe451661a',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14993',
  'x-ms-correlation-request-id': 'da3dfd55-9155-4688-8771-be7f07cec234',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120147Z:da3dfd55-9155-4688-8771-be7f07cec234',
  date: 'Thu, 05 Oct 2017 12:01:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName?api-version=2017-09-01')
  .reply(200, "{\r\n  \"name\": \"singularPrefixesName\",\r\n  \"id\": \"/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName\",\r\n  \"etag\": \"W/\\\"7cfd505c-4f76-48f8-8059-8bb183aa850d\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"description\": \"testDesc\",\r\n    \"protocol\": \"*\",\r\n    \"sourcePortRange\": \"1025-1030\",\r\n    \"destinationPortRange\": \"4242\",\r\n    \"sourceAddressPrefix\": \"10.0.0.0/16\",\r\n    \"destinationAddressPrefix\": \"11.0.0.0/24\",\r\n    \"access\": \"Allow\",\r\n    \"priority\": 1470,\r\n    \"direction\": \"Inbound\",\r\n    \"sourcePortRanges\": [],\r\n    \"destinationPortRanges\": [],\r\n    \"sourceAddressPrefixes\": [],\r\n    \"destinationAddressPrefixes\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '794',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"7cfd505c-4f76-48f8-8059-8bb183aa850d"',
  'x-ms-request-id': '6a01d3c5-d364-4f15-b988-9f535526b385',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-correlation-request-id': 'c8a462eb-687c-4735-9456-13ae93b49a15',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120148Z:c8a462eb-687c-4735-9456-13ae93b49a15',
  date: 'Thu, 05 Oct 2017 12:01:48 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName?api-version=2017-09-01')
  .reply(200, "{\r\n  \"name\": \"singularPrefixesName\",\r\n  \"id\": \"/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName\",\r\n  \"etag\": \"W/\\\"7cfd505c-4f76-48f8-8059-8bb183aa850d\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"description\": \"testDesc\",\r\n    \"protocol\": \"*\",\r\n    \"sourcePortRange\": \"1025-1030\",\r\n    \"destinationPortRange\": \"4242\",\r\n    \"sourceAddressPrefix\": \"10.0.0.0/16\",\r\n    \"destinationAddressPrefix\": \"11.0.0.0/24\",\r\n    \"access\": \"Allow\",\r\n    \"priority\": 1470,\r\n    \"direction\": \"Inbound\",\r\n    \"sourcePortRanges\": [],\r\n    \"destinationPortRanges\": [],\r\n    \"sourceAddressPrefixes\": [],\r\n    \"destinationAddressPrefixes\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '794',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"7cfd505c-4f76-48f8-8059-8bb183aa850d"',
  'x-ms-request-id': '6a01d3c5-d364-4f15-b988-9f535526b385',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-correlation-request-id': 'c8a462eb-687c-4735-9456-13ae93b49a15',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120148Z:c8a462eb-687c-4735-9456-13ae93b49a15',
  date: 'Thu, 05 Oct 2017 12:01:48 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName?api-version=2017-09-01')
  .reply(200, "{\r\n  \"name\": \"singularPrefixesName\",\r\n  \"id\": \"/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName\",\r\n  \"etag\": \"W/\\\"7cfd505c-4f76-48f8-8059-8bb183aa850d\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"description\": \"testDesc\",\r\n    \"protocol\": \"*\",\r\n    \"sourcePortRange\": \"1025-1030\",\r\n    \"destinationPortRange\": \"4242\",\r\n    \"sourceAddressPrefix\": \"10.0.0.0/16\",\r\n    \"destinationAddressPrefix\": \"11.0.0.0/24\",\r\n    \"access\": \"Allow\",\r\n    \"priority\": 1470,\r\n    \"direction\": \"Inbound\",\r\n    \"sourcePortRanges\": [],\r\n    \"destinationPortRanges\": [],\r\n    \"sourceAddressPrefixes\": [],\r\n    \"destinationAddressPrefixes\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '794',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"7cfd505c-4f76-48f8-8059-8bb183aa850d"',
  'x-ms-request-id': '3f54c530-4511-4ff3-bae3-bfd257987156',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14995',
  'x-ms-correlation-request-id': '7a0e8d68-3817-4e13-a874-88cdfe2d6777',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120149Z:7a0e8d68-3817-4e13-a874-88cdfe2d6777',
  date: 'Thu, 05 Oct 2017 12:01:48 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName?api-version=2017-09-01')
  .reply(200, "{\r\n  \"name\": \"singularPrefixesName\",\r\n  \"id\": \"/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName\",\r\n  \"etag\": \"W/\\\"7cfd505c-4f76-48f8-8059-8bb183aa850d\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"description\": \"testDesc\",\r\n    \"protocol\": \"*\",\r\n    \"sourcePortRange\": \"1025-1030\",\r\n    \"destinationPortRange\": \"4242\",\r\n    \"sourceAddressPrefix\": \"10.0.0.0/16\",\r\n    \"destinationAddressPrefix\": \"11.0.0.0/24\",\r\n    \"access\": \"Allow\",\r\n    \"priority\": 1470,\r\n    \"direction\": \"Inbound\",\r\n    \"sourcePortRanges\": [],\r\n    \"destinationPortRanges\": [],\r\n    \"sourceAddressPrefixes\": [],\r\n    \"destinationAddressPrefixes\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '794',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"7cfd505c-4f76-48f8-8059-8bb183aa850d"',
  'x-ms-request-id': '3f54c530-4511-4ff3-bae3-bfd257987156',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14995',
  'x-ms-correlation-request-id': '7a0e8d68-3817-4e13-a874-88cdfe2d6777',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120149Z:7a0e8d68-3817-4e13-a874-88cdfe2d6777',
  date: 'Thu, 05 Oct 2017 12:01:48 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName?api-version=2017-09-01', '*')
  .reply(200, "{\r\n  \"name\": \"singularPrefixesName\",\r\n  \"id\": \"/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName\",\r\n  \"etag\": \"W/\\\"27add74e-3668-4444-a1a7-8a1b50009c70\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Updating\",\r\n    \"description\": \"testDesc\",\r\n    \"protocol\": \"*\",\r\n    \"sourcePortRange\": \"64000\",\r\n    \"destinationPortRange\": \"1200-1202\",\r\n    \"sourceAddressPrefix\": \"10.0.0.0/24\",\r\n    \"destinationAddressPrefix\": \"11.0.0.0/16\",\r\n    \"access\": \"Allow\",\r\n    \"priority\": 1470,\r\n    \"direction\": \"Inbound\",\r\n    \"sourcePortRanges\": [],\r\n    \"destinationPortRanges\": [],\r\n    \"sourceAddressPrefixes\": [],\r\n    \"destinationAddressPrefixes\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '794',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'retry-after': '10',
  'x-ms-request-id': 'd282a588-5a98-4538-b0c5-aad51367009e',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/providers/Microsoft.Network/locations/westcentralus/operations/d282a588-5a98-4538-b0c5-aad51367009e?api-version=2017-09-01',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1198',
  'x-ms-correlation-request-id': 'e56decec-db9b-47ed-9ec4-9a5beaaae5b2',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120150Z:e56decec-db9b-47ed-9ec4-9a5beaaae5b2',
  date: 'Thu, 05 Oct 2017 12:01:49 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName?api-version=2017-09-01', '*')
  .reply(200, "{\r\n  \"name\": \"singularPrefixesName\",\r\n  \"id\": \"/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName\",\r\n  \"etag\": \"W/\\\"27add74e-3668-4444-a1a7-8a1b50009c70\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Updating\",\r\n    \"description\": \"testDesc\",\r\n    \"protocol\": \"*\",\r\n    \"sourcePortRange\": \"64000\",\r\n    \"destinationPortRange\": \"1200-1202\",\r\n    \"sourceAddressPrefix\": \"10.0.0.0/24\",\r\n    \"destinationAddressPrefix\": \"11.0.0.0/16\",\r\n    \"access\": \"Allow\",\r\n    \"priority\": 1470,\r\n    \"direction\": \"Inbound\",\r\n    \"sourcePortRanges\": [],\r\n    \"destinationPortRanges\": [],\r\n    \"sourceAddressPrefixes\": [],\r\n    \"destinationAddressPrefixes\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '794',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'retry-after': '10',
  'x-ms-request-id': 'd282a588-5a98-4538-b0c5-aad51367009e',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/providers/Microsoft.Network/locations/westcentralus/operations/d282a588-5a98-4538-b0c5-aad51367009e?api-version=2017-09-01',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1198',
  'x-ms-correlation-request-id': 'e56decec-db9b-47ed-9ec4-9a5beaaae5b2',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120150Z:e56decec-db9b-47ed-9ec4-9a5beaaae5b2',
  date: 'Thu, 05 Oct 2017 12:01:49 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/providers/Microsoft.Network/locations/westcentralus/operations/d282a588-5a98-4538-b0c5-aad51367009e?api-version=2017-09-01')
  .reply(200, "{\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '29',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'df923a76-6f39-4fc4-97d8-06806c4cc864',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14996',
  'x-ms-correlation-request-id': '6b32e7de-dd60-4b45-b727-7508cbf33587',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120221Z:6b32e7de-dd60-4b45-b727-7508cbf33587',
  date: 'Thu, 05 Oct 2017 12:02:20 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/providers/Microsoft.Network/locations/westcentralus/operations/d282a588-5a98-4538-b0c5-aad51367009e?api-version=2017-09-01')
  .reply(200, "{\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '29',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'df923a76-6f39-4fc4-97d8-06806c4cc864',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14996',
  'x-ms-correlation-request-id': '6b32e7de-dd60-4b45-b727-7508cbf33587',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120221Z:6b32e7de-dd60-4b45-b727-7508cbf33587',
  date: 'Thu, 05 Oct 2017 12:02:20 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName?api-version=2017-09-01')
  .reply(200, "{\r\n  \"name\": \"singularPrefixesName\",\r\n  \"id\": \"/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName\",\r\n  \"etag\": \"W/\\\"75bd5319-9ab4-468e-a6c8-01e9a59fe8dc\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"description\": \"testDesc\",\r\n    \"protocol\": \"*\",\r\n    \"sourcePortRange\": \"64000\",\r\n    \"destinationPortRange\": \"1200-1202\",\r\n    \"sourceAddressPrefix\": \"10.0.0.0/24\",\r\n    \"destinationAddressPrefix\": \"11.0.0.0/16\",\r\n    \"access\": \"Allow\",\r\n    \"priority\": 1470,\r\n    \"direction\": \"Inbound\",\r\n    \"sourcePortRanges\": [],\r\n    \"destinationPortRanges\": [],\r\n    \"sourceAddressPrefixes\": [],\r\n    \"destinationAddressPrefixes\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '795',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"75bd5319-9ab4-468e-a6c8-01e9a59fe8dc"',
  'x-ms-request-id': '6ffbe49f-1a04-4994-9f0c-383e7adc26b8',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14999',
  'x-ms-correlation-request-id': '462ee2bb-5134-4b84-9ab6-07929816b014',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120221Z:462ee2bb-5134-4b84-9ab6-07929816b014',
  date: 'Thu, 05 Oct 2017 12:02:21 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName?api-version=2017-09-01')
  .reply(200, "{\r\n  \"name\": \"singularPrefixesName\",\r\n  \"id\": \"/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName\",\r\n  \"etag\": \"W/\\\"75bd5319-9ab4-468e-a6c8-01e9a59fe8dc\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"description\": \"testDesc\",\r\n    \"protocol\": \"*\",\r\n    \"sourcePortRange\": \"64000\",\r\n    \"destinationPortRange\": \"1200-1202\",\r\n    \"sourceAddressPrefix\": \"10.0.0.0/24\",\r\n    \"destinationAddressPrefix\": \"11.0.0.0/16\",\r\n    \"access\": \"Allow\",\r\n    \"priority\": 1470,\r\n    \"direction\": \"Inbound\",\r\n    \"sourcePortRanges\": [],\r\n    \"destinationPortRanges\": [],\r\n    \"sourceAddressPrefixes\": [],\r\n    \"destinationAddressPrefixes\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '795',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"75bd5319-9ab4-468e-a6c8-01e9a59fe8dc"',
  'x-ms-request-id': '6ffbe49f-1a04-4994-9f0c-383e7adc26b8',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14999',
  'x-ms-correlation-request-id': '462ee2bb-5134-4b84-9ab6-07929816b014',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120221Z:462ee2bb-5134-4b84-9ab6-07929816b014',
  date: 'Thu, 05 Oct 2017 12:02:21 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName?api-version=2017-09-01')
  .reply(200, "{\r\n  \"name\": \"singularPrefixesName\",\r\n  \"id\": \"/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName\",\r\n  \"etag\": \"W/\\\"75bd5319-9ab4-468e-a6c8-01e9a59fe8dc\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"description\": \"testDesc\",\r\n    \"protocol\": \"*\",\r\n    \"sourcePortRange\": \"64000\",\r\n    \"destinationPortRange\": \"1200-1202\",\r\n    \"sourceAddressPrefix\": \"10.0.0.0/24\",\r\n    \"destinationAddressPrefix\": \"11.0.0.0/16\",\r\n    \"access\": \"Allow\",\r\n    \"priority\": 1470,\r\n    \"direction\": \"Inbound\",\r\n    \"sourcePortRanges\": [],\r\n    \"destinationPortRanges\": [],\r\n    \"sourceAddressPrefixes\": [],\r\n    \"destinationAddressPrefixes\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '795',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"75bd5319-9ab4-468e-a6c8-01e9a59fe8dc"',
  'x-ms-request-id': '0ad3e0e2-6782-4b27-82de-42ef1f150884',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14996',
  'x-ms-correlation-request-id': 'a5812dc8-6b13-46f8-9ed3-074d2a481c60',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120223Z:a5812dc8-6b13-46f8-9ed3-074d2a481c60',
  date: 'Thu, 05 Oct 2017 12:02:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName?api-version=2017-09-01')
  .reply(200, "{\r\n  \"name\": \"singularPrefixesName\",\r\n  \"id\": \"/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName\",\r\n  \"etag\": \"W/\\\"75bd5319-9ab4-468e-a6c8-01e9a59fe8dc\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"description\": \"testDesc\",\r\n    \"protocol\": \"*\",\r\n    \"sourcePortRange\": \"64000\",\r\n    \"destinationPortRange\": \"1200-1202\",\r\n    \"sourceAddressPrefix\": \"10.0.0.0/24\",\r\n    \"destinationAddressPrefix\": \"11.0.0.0/16\",\r\n    \"access\": \"Allow\",\r\n    \"priority\": 1470,\r\n    \"direction\": \"Inbound\",\r\n    \"sourcePortRanges\": [],\r\n    \"destinationPortRanges\": [],\r\n    \"sourceAddressPrefixes\": [],\r\n    \"destinationAddressPrefixes\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '795',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"75bd5319-9ab4-468e-a6c8-01e9a59fe8dc"',
  'x-ms-request-id': '0ad3e0e2-6782-4b27-82de-42ef1f150884',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14996',
  'x-ms-correlation-request-id': 'a5812dc8-6b13-46f8-9ed3-074d2a481c60',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120223Z:a5812dc8-6b13-46f8-9ed3-074d2a481c60',
  date: 'Thu, 05 Oct 2017 12:02:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .delete('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName?api-version=2017-09-01')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/providers/Microsoft.Network/locations/westcentralus/operationResults/a57e2da7-8605-472e-835d-6cb2f28fc8ab?api-version=2017-09-01',
  'retry-after': '10',
  'x-ms-request-id': 'a57e2da7-8605-472e-835d-6cb2f28fc8ab',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/providers/Microsoft.Network/locations/westcentralus/operations/a57e2da7-8605-472e-835d-6cb2f28fc8ab?api-version=2017-09-01',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1196',
  'x-ms-correlation-request-id': '489bac6f-5bcb-4ddd-b476-99db01813b5d',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120224Z:489bac6f-5bcb-4ddd-b476-99db01813b5d',
  date: 'Thu, 05 Oct 2017 12:02:23 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .delete('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/xplat-test-rule/providers/Microsoft.Network/networkSecurityGroups/networkSecurityGroupName/securityRules/singularPrefixesName?api-version=2017-09-01')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/providers/Microsoft.Network/locations/westcentralus/operationResults/a57e2da7-8605-472e-835d-6cb2f28fc8ab?api-version=2017-09-01',
  'retry-after': '10',
  'x-ms-request-id': 'a57e2da7-8605-472e-835d-6cb2f28fc8ab',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/providers/Microsoft.Network/locations/westcentralus/operations/a57e2da7-8605-472e-835d-6cb2f28fc8ab?api-version=2017-09-01',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1196',
  'x-ms-correlation-request-id': '489bac6f-5bcb-4ddd-b476-99db01813b5d',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120224Z:489bac6f-5bcb-4ddd-b476-99db01813b5d',
  date: 'Thu, 05 Oct 2017 12:02:23 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/providers/Microsoft.Network/locations/westcentralus/operations/a57e2da7-8605-472e-835d-6cb2f28fc8ab?api-version=2017-09-01')
  .reply(200, "{\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '29',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'fb244e73-c2a0-46c4-be2d-49410f462eeb',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14992',
  'x-ms-correlation-request-id': '9d9267bf-3ab0-47c8-8e3e-d58794dab8b7',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120255Z:9d9267bf-3ab0-47c8-8e3e-d58794dab8b7',
  date: 'Thu, 05 Oct 2017 12:02:55 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/providers/Microsoft.Network/locations/westcentralus/operations/a57e2da7-8605-472e-835d-6cb2f28fc8ab?api-version=2017-09-01')
  .reply(200, "{\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '29',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'fb244e73-c2a0-46c4-be2d-49410f462eeb',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14992',
  'x-ms-correlation-request-id': '9d9267bf-3ab0-47c8-8e3e-d58794dab8b7',
  'x-ms-routing-request-id': 'WESTEUROPE:20171005T120255Z:9d9267bf-3ab0-47c8-8e3e-d58794dab8b7',
  date: 'Thu, 05 Oct 2017 12:02:55 GMT',
  connection: 'close' });
 return result; }]];