// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '2c224e7e-3ef5-431d-a57b-e71f4662e3a6',
    name: 'Node CLI Test',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    _eventsCount: '1',
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_VM_TEST_LOCATION'] = 'westus';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-probe/providers/Microsoft.Network/loadBalancers/loadBalancerName?api-version=2017-06-01')
  .reply(200, "{\r\n  \"name\": \"loadBalancerName\",\r\n  \"id\": \"/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-probe/providers/Microsoft.Network/loadBalancers/loadBalancerName\",\r\n  \"etag\": \"W/\\\"dd3d5595-6889-4c28-99bf-955afa822127\\\"\",\r\n  \"type\": \"Microsoft.Network/loadBalancers\",\r\n  \"location\": \"westus\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"resourceGuid\": \"d95c85ac-e198-4801-a5cb-2ce619f10b15\",\r\n    \"frontendIPConfigurations\": [\r\n      {\r\n        \"name\": \"frontendIPConfigurationName\",\r\n        \"id\": \"/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-probe/providers/Microsoft.Network/loadBalancers/loadBalancerName/frontendIPConfigurations/frontendIPConfigurationName\",\r\n        \"etag\": \"W/\\\"dd3d5595-6889-4c28-99bf-955afa822127\\\"\",\r\n        \"properties\": {\r\n          \"provisioningState\": \"Succeeded\",\r\n          \"privateIPAllocationMethod\": \"Dynamic\",\r\n          \"publicIPAddress\": {\r\n            \"id\": \"/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-probe/providers/Microsoft.Network/publicIPAddresses/publicIPAddressName\"\r\n          }\r\n        }\r\n      }\r\n    ],\r\n    \"backendAddressPools\": [],\r\n    \"loadBalancingRules\": [],\r\n    \"probes\": [],\r\n    \"inboundNatRules\": [],\r\n    \"outboundNatRules\": [],\r\n    \"inboundNatPools\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1342',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"dd3d5595-6889-4c28-99bf-955afa822127"',
  'x-ms-request-id': 'c4234bb0-8d77-4d21-af35-97a2321e70d3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14993',
  'x-ms-correlation-request-id': '5358ccd7-c457-4151-bc0f-deb107c43d5a',
  'x-ms-routing-request-id': 'WESTEUROPE:20170605T073443Z:5358ccd7-c457-4151-bc0f-deb107c43d5a',
  date: 'Mon, 05 Jun 2017 07:34:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-probe/providers/Microsoft.Network/loadBalancers/loadBalancerName?api-version=2017-06-01')
  .reply(200, "{\r\n  \"name\": \"loadBalancerName\",\r\n  \"id\": \"/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-probe/providers/Microsoft.Network/loadBalancers/loadBalancerName\",\r\n  \"etag\": \"W/\\\"dd3d5595-6889-4c28-99bf-955afa822127\\\"\",\r\n  \"type\": \"Microsoft.Network/loadBalancers\",\r\n  \"location\": \"westus\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"resourceGuid\": \"d95c85ac-e198-4801-a5cb-2ce619f10b15\",\r\n    \"frontendIPConfigurations\": [\r\n      {\r\n        \"name\": \"frontendIPConfigurationName\",\r\n        \"id\": \"/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-probe/providers/Microsoft.Network/loadBalancers/loadBalancerName/frontendIPConfigurations/frontendIPConfigurationName\",\r\n        \"etag\": \"W/\\\"dd3d5595-6889-4c28-99bf-955afa822127\\\"\",\r\n        \"properties\": {\r\n          \"provisioningState\": \"Succeeded\",\r\n          \"privateIPAllocationMethod\": \"Dynamic\",\r\n          \"publicIPAddress\": {\r\n            \"id\": \"/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-probe/providers/Microsoft.Network/publicIPAddresses/publicIPAddressName\"\r\n          }\r\n        }\r\n      }\r\n    ],\r\n    \"backendAddressPools\": [],\r\n    \"loadBalancingRules\": [],\r\n    \"probes\": [],\r\n    \"inboundNatRules\": [],\r\n    \"outboundNatRules\": [],\r\n    \"inboundNatPools\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1342',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"dd3d5595-6889-4c28-99bf-955afa822127"',
  'x-ms-request-id': 'c4234bb0-8d77-4d21-af35-97a2321e70d3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14993',
  'x-ms-correlation-request-id': '5358ccd7-c457-4151-bc0f-deb107c43d5a',
  'x-ms-routing-request-id': 'WESTEUROPE:20170605T073443Z:5358ccd7-c457-4151-bc0f-deb107c43d5a',
  date: 'Mon, 05 Jun 2017 07:34:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-probe/providers/Microsoft.Network/loadBalancers/loadBalancerName?api-version=2017-06-01', '*')
  .reply(400, "{\r\n  \"error\": {\r\n    \"code\": \"InvalidRequestFormat\",\r\n    \"message\": \"Cannot parse the request.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"InvalidJson\",\r\n        \"message\": \"JSON integer 2147483650 is too large or small for an Int32. Path 'properties.probes[0].properties.intervalInSeconds', line 1, position 901.\"\r\n      },\r\n      {\r\n        \"code\": \"InvalidJson\",\r\n        \"message\": \"Could not find member 'name' on object of type 'LoadBalancerProbeProperties'. Path 'properties.probes[0].name', line 1, position 910.\"\r\n      },\r\n      {\r\n        \"code\": \"InvalidJson\",\r\n        \"message\": \"Unexpected token when deserializing object: EndArray. Path 'properties.probes', line 1, position 951.\"\r\n      },\r\n      {\r\n        \"code\": \"InvalidJson\",\r\n        \"message\": \"Unexpected token while deserializing object: PropertyName. Path 'properties.inboundNatRules', line 1, position 970.\"\r\n      },\r\n      {\r\n        \"code\": \"InvalidJson\",\r\n        \"message\": \"Infinite loop detected from error handling. Path 'properties.inboundNatRules', line 1, position 972.\"\r\n      }\r\n    ]\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1087',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'ebddd561-7d3f-404a-be2d-a2882d54ab0f',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1196',
  'x-ms-correlation-request-id': '1a919870-24e5-4cbe-b691-0e2ab985868d',
  'x-ms-routing-request-id': 'WESTEUROPE:20170605T073444Z:1a919870-24e5-4cbe-b691-0e2ab985868d',
  date: 'Mon, 05 Jun 2017 07:34:43 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplat-test-probe/providers/Microsoft.Network/loadBalancers/loadBalancerName?api-version=2017-06-01', '*')
  .reply(400, "{\r\n  \"error\": {\r\n    \"code\": \"InvalidRequestFormat\",\r\n    \"message\": \"Cannot parse the request.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"InvalidJson\",\r\n        \"message\": \"JSON integer 2147483650 is too large or small for an Int32. Path 'properties.probes[0].properties.intervalInSeconds', line 1, position 901.\"\r\n      },\r\n      {\r\n        \"code\": \"InvalidJson\",\r\n        \"message\": \"Could not find member 'name' on object of type 'LoadBalancerProbeProperties'. Path 'properties.probes[0].name', line 1, position 910.\"\r\n      },\r\n      {\r\n        \"code\": \"InvalidJson\",\r\n        \"message\": \"Unexpected token when deserializing object: EndArray. Path 'properties.probes', line 1, position 951.\"\r\n      },\r\n      {\r\n        \"code\": \"InvalidJson\",\r\n        \"message\": \"Unexpected token while deserializing object: PropertyName. Path 'properties.inboundNatRules', line 1, position 970.\"\r\n      },\r\n      {\r\n        \"code\": \"InvalidJson\",\r\n        \"message\": \"Infinite loop detected from error handling. Path 'properties.inboundNatRules', line 1, position 972.\"\r\n      }\r\n    ]\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1087',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'ebddd561-7d3f-404a-be2d-a2882d54ab0f',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1196',
  'x-ms-correlation-request-id': '1a919870-24e5-4cbe-b691-0e2ab985868d',
  'x-ms-routing-request-id': 'WESTEUROPE:20170605T073444Z:1a919870-24e5-4cbe-b691-0e2ab985868d',
  date: 'Mon, 05 Jun 2017 07:34:43 GMT',
  connection: 'close' });
 return result; }]];
